version: 2
jobs:
  vuex-store-test:
    docker:
      - image: circleci/node:8.9.0

    steps:
      - checkout
      - restore-cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-
      
      - run : npm install

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
          - ./node_modules

      - run : npm run test:unit
workflows:
  version: 2
  test:
    jobs:
      - vuex-store-test:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/