version: 2
jobs:
  test:
    branches:
      ignore:
        - develop
        - /feature-.*/
    docker:
      - image: circleci/node:8.9.0

    steps:
      - checkout
      - restore-cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      
      - run : npm install

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
          - ./node_modules

      - run : npm run test:unit